### ISSUE TITLE
NTHREADS_ in form and parform?

### ISSUE THREAD

**Issue by tueda** [vermaseren/form#159]
What it the actual meaning of `NTHREADS_` in FORM and ParFORM? It just gives the number set by `-w` plus 1:
```
$ form -w100 1
FORM 4.1 (Nov 29 2016, v4.1-20131025-272-gb993ca7) 64-bits  Run: Tue Dec 13 19:41:18 2016
    #show
#The preprocessor variables:
13: NPARALLELTASKS_ = "1"
15: NTHREADS_ = "101"
```
But should it be always 1?

I'm trying to write a sort of canonicalization, and it has a structure like
```
#call CanonicalizeInEachWorker()
#call CanonicalizeOnMaster()
```
such that the first one has benefit from parallelization, while the second one guarantees the uniqueness. But in the sequential mode, it performs the same thing twice. So I would skip one of them if there is no benefit from parallelization, determined from the values of `NPARALLELTASKS_` and `NTHREADS_`. (Or other methods?)

**Comment by vermaseren** [comment]
Hi Takahiro,

I think you ran into another dinosaur.
After the sortbots were introduced there can be more threads. Also in various versions of linux,
(older ones) there was even one more thread that sat above the master thread. That was somehow sneaked in
by the OS. I had no control over that.
I am not sure what you want exactly. Just make it such that it performs as you need it to perform, and then,
most likely nobody will complain. Very likely this is hardly ever used, and if people use it, they will let it be
known and then we have to figure out how to combine the old and the new.
These variable were made because it might or might not be useful. Often I guessed right and often I guessed
wrong.

Cheers

Jos

**Comment by tueda** [comment]
Hi Jos,

What I want to do is to know from a FORM program which version (say, FORM or TFORM) the user is running. At first I thought `NTHREDS_` can distinguish TFORM from FORM, but if the user (mistakenly) runs the program with `form -w8`, then `NTHREADS_` becomes 9 even though the sequential FORM can't utilize 8 (+1 or more) cores.

**Comment by vermaseren** [comment]
Hi Takahiro,

That form -w8  looks indeed like an error if it gives NTHREADS_ as 9.
When you are busy at it, you can change that.

Cheers

Jos

**Comment by tueda** [comment]
OK. I will make a change such that `NTHREADS_` gets 1 in the sequential FORM and ParFORM.
