### ISSUE TITLE
Nested bracket

### ISSUE THREAD

**Issue by gkdgoutam** [vermaseren/form#301]
Hi,
not an issue but a small curiosity. I wanted to ask experts if a nested bracket is possible in Form output.

An example is like this:

    L exp= (3*CA*CF + 5*CA*CF*zeta2 + 17*zeta3*NF*CF);
    b CA,CF,NF;
    Print +s exp;

This will give me output
    
    + CA*CF*( + 3 + 5*zeta2 ) 
    + CF*NF*( + 17*zeta3);

But I was wondering if this is also possible to take zeta bracket in a nested way so that I will have

    CA*CF*( 
    + 3
    + zeta2*(5)
    )
    + CF*NF*(
    + zeta3*(17)
    )

PS. apologies if this is not the right platform to ask.

**Comment by vermaseren** [comment]
Hi,

I have several times started on an implementation, thinking it would be trivial, but every time
I ran into some complications, and due to other activities had to stop it.
The internal notation of the terms does allow it though. The bracket separator (separates the parts
outside from the part inside) has a space for a bracket level, already from the beginning. The sorting
routines can handle it also. The main problems are: syntax (how to declare) and taking the terms
apart into their verious levels. Then there is also the problem of selecting the contents of a bracket
as in F[x^2] when F is an expression. The syntax for that needs also some thinking. Plus that it
becomes rather messy for the bracketindex as well.
As you see, at first it looks trivial, but…..
My guess is that it would be a project for a couple of days full time, which are hard to find.

Jos

**Comment by vermaseren** [comment]
Yes, I forgot.
That was precisely what the function dum_ was made for.

Thanks

Jos

**Comment by gkdgoutam** [comment]
Thanks. I also wanted to ask one more question related to this. Apart from the `format` is there anything for output optimisation? Particularly I could not find any easier way if I can print the output in a reverse order than the normal one.

**Comment by vermaseren** [comment]
Printing the output in reverse form does not exist.
There exists however the #reverseinclude that can do reverse reading of the input.
Maybe you can make that work for you?

Jos

**Comment by gkdgoutam** [comment]
Thanks. I also had similar plans i.e. multiply by dummy flag and remove those in using shell script. 
Thanks you.

**Comment by gkdgoutam** [comment]
Thanks. I also had similar plans i.e. multiply by dummy flag and remove those in using shell script. 
Thanks you.
