### ISSUE TITLE
Missed syntax error in Fill statement rhs

### ISSUE THREAD

**Issue by jodavies** [vermaseren/form#317]
In the following, FORM proceeds with no error.
```
Symbol x;          
Table tab(0:1);    
                   
Fill tab(0) = 1 x; 
*Fill tab(1) = 1 x;
                   
.end               
```
If one uncomments the second `Fill` statement, FORM reports
```
test.frm Line 5 --> Warning: Table element was already defined. New definition
will be used
```

Thanks,
Josh.

**Comment by vermaseren** [comment]
As it should!
 tab(0) = 1 x; is interpreted as tab(0) = 1,x; as explained in the manual.
And with 1,x it fill two table elements. and hence the compiler is right.

Btw. I also run sometimes into tricky things like this where you just don’t see what went
wrong, until suddenly you see something seemingly insignificant and it turns out that
indeed the compiler was right.

Cheers

Jos

**Comment by jodavies** [comment]
Ah, OK! I didn't realize that that syntax for filling multiple elements was allowed.

Thanks!
