### ISSUE TITLE
Wrong implicit symbol declaration in "autodeclare index" 

### ISSUE THREAD

**Issue by mgerlach-phys** [vermaseren/form#324]
The following, short program does not behave as expected:

`*symbol n;
autodeclare index randomIndex=n;
local A =  n;  

print +s; 
.end`

Without declaring "n" the expected behavior would be to declare it implicitly as a symbol with a warning (as it is the case for the program without the "autodeclare" statement).

Funnily, the program runs without complains and returns `i_`.

**Comment by tueda** [comment]
Thank you for your report!
It seems that this issue and #325 are caused by the fact that `n` (in the following example) is considered as a different object from the usual one when implicitly used via `autodeclare index` (`20` vs. `0`):
```form
I x = n;
L F = n;
P "%r";
.end
```
```
test.frm Line 1 --> Warning: Implicit declaration of n as a symbol
8  1  4  20  1  1  1  3
```


```form
Auto I x = n;
L F = n;
P "%r";
.end
```
```
8  1  4  0  1  1  1  3
```
The reason why you may get `i_`, `pi_`, `coeff_`, `num_`, `den_`, ... is because they are built-in objects defined in this order:
https://github.com/vermaseren/form/blob/0b3ab5d87b7aa61408f57bcd041707f43cc8961b/sources/startup.c#L1029-L1037
