### ISSUE TITLE
I can't build doc manual in cygwin

### ISSUE THREAD

**Issue by FeelUsM** [vermaseren/form#383]
in directory form/doc/manual:
```
$ make html
/bin/sh "../../scripts/git-version-gen.sh" -C "." -t -o version.tex --date-format '%e %B %Y'
mkdir -p html
/cygdrive/c/Program Files/MiKTeX/miktex/bin/x64/htlatex manual "html,mathml-" "" "-dhtml/"
/bin/sh: /cygdrive/c/Program: No such file or directory
make: *** [Makefile:541: html/manual.html] Error 127
```
`/cygdrive/c/Program Files/MiKTeX/miktex/bin/x64/htlatex` must be enclosed in quotation marks

I don't know, may be it is autotools' error, but it's worth checking out

**Comment by tueda** [comment]
> /cygdrive/c/Program Files/MiKTeX/miktex/bin/x64/htlatex manual "html,mathml-" "" "-dhtml/"

Here you are running `htlatex` installed on Windows, which causes a space in the path name. Maybe you need to `htlatex` installed via the Cygwin installer.

**Comment by tueda** [comment]
The problem comes from the fact that `AC_PATH_PROG` may return a path including spaces (according to [this post](https://narkive.com/wt5EFotb:2.448.12)) without quotes. `AC_PATH_PROG` is used in

https://github.com/vermaseren/form/blob/b0e72a834eb5d1d057e91202201ff21013838be4/configure.ac#L934

As a workaround, in principle, it is possible to quote `$(HTLATEX)` at

https://github.com/vermaseren/form/blob/b0e72a834eb5d1d057e91202201ff21013838be4/doc/manual/Makefile.am#L109

But then we might start to think of all similar usages in Makefiles `$(LATEX)`, `$(RUBY)`, `$(CC)` etc., many things...
