### ISSUE TITLE
Buffer too small in PasteTerm?

### ISSUE THREAD

**Issue by magv** [vermaseren/form#402]
Hi, folks. I'm getting this error from the latest tform:
```
[...]
Buffer too small in PasteTerm

   18  241  5  0  4294967280  357  1  4  89  1  6  5  1771  82003  0  1  2  3

Called from Generator

   18  241  5  0  4294967280  357  1  4  58  82003  6  5  1730  1  0  1  1  3

Called from Generator

   26  241  5  0  4294967280  357  6  13  2  1  0  5  4  3494967100  
   3494967103  5  4  3494967101  3494967102  1  4  58  82003  1  1  3
Called from Generator

   14  241  5  1  4294967280  357  6  5  357  1  2  1  1  3
Called from Generator
Called from ExtraSymFun

   14  241  5  1  4294967280  357  91  5  1  4294967280  357  1  1  3
Called from Generator

   9  6  5  1  1  0  1  1  3
Called from Generator
Error in processing one term in thread 1 in module 59
Program terminating in thread 1 at sort Line 2 --> 
```

Could you tell me which buffer is too small? What option should I increase?

**Comment by vermaseren** [comment]
Typically this would be MaxTermSize.
One of the problems here is that if you have high powers of an expression
it pastes the individual terms together and then later it lets the normalisation
routine sort that out. This means that (a*b+c*d)^10 may have temporarily
terms like a*b*a*b*a*b*a*b*a*b*a*b*a*b*a*b*a*b*a*b and mixtures.

This could be mended by using a special buffer there that can be adjusted, but 
then, if this does not collapse in the normalisation routine, that routine will crash
because after normalisation everything MUST fit inside MaxTermSize.

Making MaxTermSize arbitrarily big to avoid all this runs into memory problems.
Hence, if just raising MaxTermSize to a reasonable size does not work, one may
have to look at the problem again and program things (slightly) differently. In the
above example that could be
id abcd10 = sum_(j,1,10,a^j*b^j*c^(10-j)*d^(n-j)*binom_(10,j));
or whatever elese may be handy.

The above may be rather primitive but it is part of what makes Form fast, although
I am not claiming that a bit more thinking here may make it better and not loose
speed or make it even faster.

**Comment by vermaseren** [comment]
In this example the id x=1; makes basically 12345 substitutions
and pastes those together, because Form does not look into the rhs
to decide the strategy.
The much more efficient statement is
id  x^n? = 1;
That is just a single operation.
You are right that x^123 takes less space than TAG(123).

**Comment by magv** [comment]
You're right, thanks; I'll use `id  x^n? = 1;`, which solves the problem in my code.

I guess the "Buffer too small in PasteTerm" error message could still use an improvement.
