### ISSUE TITLE
Clarify extcmd.c license

### ISSUE THREAD

**Issue by antero-0** [vermaseren/form#431]
Regarding this comment in ```extcmd.c```:

```
The code of this module
	is NOT covered by GPL; it can be used under the terms of the FORM 
	License http://www.nikhef.nl/~form/license.html
```

Is this comment still valid after the file was rewritten by M. Tentyukov in 2006? If so I think it may prevent FORM from being packaged for free software package repositories. The above link no longer works, but accessing it through an archive shows terms 2 and 3 are non-free.

Would it be possible for the comment to be removed if it is no longer valid, or update COPYING to reflect the non-free components so package maintainers are aware? Thank you.

**Comment by tueda** [comment]
Thank you for pointing it out.

This comment was introduced in the commit https://github.com/vermaseren/form/commit/bd7f0b536ddf167701134febec12b9a1b0dbbcd9 by Misha Tentyukov in 2004. At that time, FORM adopted the old FORM licence. I guess he wanted to explicitly declare that the code was covered by the old FORM licence, instead of the GPL2 that was adopted in the DIANA project ([clone](https://github.com/apik/diana)). Because the whole FORM source code licence has been changed from the old FORM licence to the GPL3-or-later since in 2010 (https://github.com/vermaseren/form/compare/079398e...3ed0a65), I think this comment in `extcmd.c` is invalid and the sentence should be removed.

@vermaseren Jos, am I right?

For reference: the old FORM license (in the Internet Archive):
- https://web.archive.org/web/20060924081011/http://www.nikhef.nl:80/~form/license.html

**Comment by vermaseren** [comment]
I think you got it right.
The file extcmd.c was made by Misha Tentyukov and has basically never been tampered much
by others. We switched to the GPL3 on the advise of Jens Vollinga who did not like the Form
license very much and according to him it was incompatible with the GPL. It is clear that we forgot
to take out that commentary in extcmd.c because at the time nobody in the team felt responsible
for it. I just hope there are no more of those comments around. Maybe we can mention somewhere
that the GPL holds for all the Form sources and any mention of the Fprm license should by now
be considered obsolete and invalid.

**Comment by tueda** [comment]
Thanks for the explanation. It seems that this sentence is the only one that mentions the old FORM license:
```
$ rg'form/license'
sources/extcmd.c
40:     License http://www.nikhef.nl/~form/license.html
```
I will push a commit to remove this sentence from the commentary in `extcmd.c`.
