### ISSUE TITLE
Terminating the program immediately if a load instruction fails

### ISSUE THREAD

**Issue by vsht** [vermaseren/form#595]
Hi,

in my understanding if FORM fails to load the given file (i.e. because it doesn't exist), the execution somehow still
continues until the very end but the program will ultimately crash, e.g.

```
Auto S a,b;
Auto CF fun;
L exp = (a+b)^4;
.sort

Load iDontExist.res;
.sort

#message Here 1
id a^2 = a2;
.sort
print;

#message Here 2
id b^2 = b2;
.sort

.end
```

I think that it would be nice if one could interrupt the execution immediately after even a single load statement fails. This would make the analysis of log files so much easier, because one wouldn't need to scroll backwards through pages of useless messages.

Is there a simple way to achieve this?

Cheers,
Vlad

**Comment by jodavies** [comment]
It should be straightforward to terminate on error in CoLoad. Since it is ultimately an error anyway it should not break anyone's scripts.

The issue I suppose is that returning -1 from CoLoad doesn't terminate form immediately. I am not sure why there is this `return(MesPrint(...))` pattern here, though `MesPrint` does return -1.

**Comment by vsht** [comment]
May be one could add an option for terminating immediately? So one would for sure preserve any workflow that
might rely on the current behavior.

**Comment by jodavies** [comment]
I think the reason why, in general, compiler errors don't terminate immediately is that it can be useful to attempt to proceed. Suppose you `#include` a file which has undefined symbols, it is nice to see a list of all of them in a single run, rather than repeatedly running and adding a single symbol.

Here you might use load multiple times and it is nice to know that files other than the first were also not found in a single run. So in some sense terminating immediately might actually "break a workflow"...

Maybe an easy workaround on your side would be to wrap Load in a procedure which checks existence of the file with `#system` and terminates if the file is not found?

**Comment by vsht** [comment]
Yeah, I guess that would work. The extra IO on the OS side might be not so good when adding many amplitudes together, though

Am 29. November 2024 16:43:31 UTC schrieb jodavies ***@***.***>:

**Comment by jodavies** [comment]
Well it is only a trivial amount of IO for the filesystem. For my own projects I use the following. Particularly if all of your files are stored on network storage, this saves a lot of capacity and network bandwidth while saving and loading.

One minor irritation is there must not be any spaces after the commas in the `#call`.

```
#ifndef `FORMTMP'
	#message GzUtil.h: Error: FORMTMP not defined.
	#terminate
#endif

#procedure GzLoad(DIR,NAME)
	#$exists =
		#pipe if [ -f `DIR'/`NAME'.gz ]; then echo 1; else echo 0; fi
		;
	#if `$exists' == 0
		#message GzLoad: Error: File does not exist: `DIR'/`NAME'.gz
		#terminate
	#else
		#message GzLoad: Loading `DIR'/`NAME'
	#endif

	#system gunzip < `DIR'/`NAME'.gz > `FORMTMP'/`NAME'
	Load `FORMTMP'/`NAME';
	#system rm `FORMTMP'/`NAME'

#endprocedure


#procedure GzSave(DIR,NAME,EXPR)
	Save `FORMTMP'/`NAME' , `EXPR';
	#system gzip < `FORMTMP'/`NAME' > `DIR'/`NAME'.gz
	#system rm `FORMTMP'/`NAME'
#endprocedure
```

**Comment by jodavies** [comment]
OK, then let's mark this as wontfix for now since there is a workaround. One day the wontfix issues can be re-evaluated...

**Comment by tueda** [comment]
[Josh's workaround](https://github.com/vermaseren/form/issues/595#issuecomment-2508541717) is another use case of `fileexists`, #240.

**Comment by jodavies** [comment]
Yes, this would be a cleaner way to do this ultimately. Also my workaround would fail on windows. Maybe FORM5 is a good time to add #240, since it is not very hard to do.
