### ISSUE TITLE
antibrackets and table

### ISSUE THREAD

**Issue by vsht** [vermaseren/form#66]
I'm wondering if there is a limitation that one cannot use __antibrackets__ with __table__ elements. For example 

```
S a,b,c,d,e,f;
CFunction cfun;
Table B(1:2);
Fill B(1) = b;
Fill B(2) = c;
L x = (a+b)^4*(c+d)^4*(e+f)^4;
.sort
antibrackets B(1),B(2);
.sort
collect cfun;
print;
.end
```
runs without errors, but b and c are not put into cfun. If I replace `antibrackets B(1),B(2)` with `antibrackets b,c` then I get the desired result. I checked the manual carefully, but couldn't find anything mentioning this issue.

Actually my goal is to have `antibrackets` inside a `procedure` with a variable number of symbolic arguments, so I though that putting the arguments inside a table and then using them as table elements should do the job. Apparently it doesn't seem to work.

**Comment by vermaseren** [comment]
Hi,

The (anti)bracket statement is more a declaration than something executable.
In my version it gives a warning like:

    antibrackets B(1),B(2);
a.frm Line 8 --> Illegal separator: brackets,B(

because the bracket statement expects just simple variables. Table elements are not substituted
in such a ‘declaration’. If you insist on putting those table elements there you have to be a bit more
indirect as in

.sort
#$B1 = B(1);
#$B2 = B(2);
antibrackets `$B1’,`$B2’;

The evaluation of the dollars does make the table substitution. Again the bracket statement does not
substitute dollars, but here you can circumvent that by having the preprocessor do it.

I hope this clarifies a bit.

Jos

**Comment by vsht** [comment]
Hi,

thanks, this really helps. 

Now I have my function working, although to have an "arbitrary" number of arguments I need to use a switch instruction like 


```
#switch `n'
#case 1
  #$B1 = `tab'(1);
  antibrackets `$B1';
#break
#case 2
  #$B1 = `tab'(1);
  #$B2 = `tab'(2);
  antibrackets `$B1',`$B2';
```
This is because something like 

```
  S a,b,c,d,e,f;
CFunction cfun;
Table B(1:3);
Fill B(1) = b;
Fill B(2) = c;
Fill B(3) = d;
L z= 3;
L x = (a+b)^4*(c+d)^4*(e+f)^4;
.sort
#$B1 = B(1);
#$B2 = B(2);
#$B3 = B(3);
#$n = z;
* antibrackets `$B1',`$B2',`$B3';
antibrackets `$B1',...,`$B`$n'';
.sort
collect cfun;
print;
.end
```
doesn't work. It's also clear why, but I guess that there is no simple way to tell the preprocessor to first write out the triple dot operator and then substitute the table elements.

**Comment by vermaseren** [comment]
Hi Vladislav,

You can do that with the preprocessor do-loop.
#do i = 1,`n’
  #$B`i’’ = `tab’(`i’);
#enddo
antibrackets
#do i = 1,`n’
    `$B`i’'
#enddo
    ;
This way you will never have to worry about this again, unless you get the case `n’ == 0.

Jos

**Comment by vsht** [comment]
Hi Jos,

thanks. I figured out that I could do something like

```
AutoDeclare Symbol vv;
#do i = 1,`n'
  id `tab'(`i')  = vv`i';
#enddo
antibrackets vv1,...,vv`n';
.sort
collect `head';
argument;
#do i = 1,`n'
  id vv`i' =  `tab'(`i');
#enddo
endargument;
```
as a workaround, but your solution is of course much better and faster. A __#do__ loop as an argument for __antibrackets__ is really a nice trick that I'll try to remember.

Best,
Vladyslav
