### ISSUE TITLE
Teach transform how to apply linearity?

### ISSUE THREAD

**Issue by vsht** [vermaseren/form#67]
Hi,

please forgive my ignorance, if I'm suggesting something stupid/obviously wrong, but I wonder if it would make sense to add an option to `transform` for applying linearity, i.e. rewriting something like
`f(2a+5b-3c)` into `2 f(a) + 5 f(b) - 3 f(c)`. I know that one can do it with existing FORM commands, e.g. like in

```
#procedure linearize(head);
CFun tmphead;
S tmpx,tmpy;
SplitArg,`head';
repeat;
id `head'(tmpx?,?tmpy) =  tmphead(tmpx)+ `head'(?tmpy);
id `head'() = 0;
endrepeat;
MakeInteger,tmphead;
Multiply replace_(tmphead,`head');
#endprocedure

CFun fff;
AutoDeclare S v;
L res = fff(2*v1+3*v2-8*v3+9*v4+24*v5);
.sort
#call linearize(fff);
print;
.end

```

but to my (very limited) FORM knowledge, there is no way to avoid `repeat` here if one insists on the arguments being symbols. On the other hand, one could probably do this much faster internally, if one could write sth like `transform,fff,linearity'  for that.  Especially since FORM can apply linearity for vectors

```
CFun fff;
AutoDeclare V v;
Index i;
L res = fff(2*v1+3*v2-8*v3+9*v4+24*v5);
.sort
id fff(i?) = fff(i);
print;
.end
```

I believe that it would not be too difficult to add that functionality for symbols as well.

Cheers,
Vladyslav

**Comment by vermaseren** [comment]
Hi Vladyslav,

You are fully right that it is probably not too much work. But it does require a certain amount of
care and there are only so many hours in a day, and I also like to do big calculations with FORM.
Hence things that have a workaround are usually not very high on the list unless the time gain is
spectacular. In this case the command would be a cousing of chainout, say chainsplit. Your program
would then be
     SplitArg head;
     ChainSplit head;
     Normalize head;
By the way, Normalize works slightly better than MakeInteger, because makeinteger does not look at
the sign of the argument and Normalize does.
As is, I would say:
    SplitArg,head;
    Repeat id head(x?,y?,?a) = head(x)*head(y,?a);
    Normalize head;
This repeat terminates the way you like it. It does have the repeat though and hence n-1 (easy)
pattern matchings for n arguments.

Cheers

Jos

**Comment by vsht** [comment]
Hi Jos,

thanks for your reply, I understand.

Cheers,
Vladyslav
