### ISSUE TITLE
Exhausting disk space when a $-variable doesn't fit in the sub-large buffer

### ISSUE THREAD

**Issue by tueda** [vermaseren/form#80]
With the default setup parameters (Linux x86_64), the following program starts to make a big `xformxxx.sf2` file and seems to enter an infinite loop:

```
S x1,...,x1000;
CF f;
L F = 1;
$x = f((x1+...+x20)^3);
inside $x;
  multiply x1+...+x248;
endinside;
.end
```

If I change `x248` to `x247`, it immediately finishes.

**Comment by vermaseren** [comment]
I guess you are in uncharted territory here.
The $ variables (and function arguments) were never meant for big things.
The $-s use the same buffers as the function arguments for sorting and when you sent these function
buffers into stage4 or worse you may run into things nobody ever tested.
If you really have to do such big things in dollar variables, you better raise the sizes of the various
buffers that are used for this.

Jos

**Comment by jodavies** [comment]
I was looking at this one because it seems similar to several other sorting-related issues that are currently open. It is a stagesort (but not a stage4 sort), it is merging two file patches at the end of the sort.

Eventually it hits a valgrind error, because it reads out of bounds when it hits:
https://github.com/vermaseren/form/blob/0112aa6b21b48616575c6cd205ec00c7797dbc93/sources/sort.c#L2619-L2620
with `*t2=266`. Next iteration `*t1=266`, and after that it looks like it gets stuck in a loop, creating the large file.

The term data in (one of?) the patches gets corrupted somewhere, it looks like.
